version: "3.8"

services:
  django:
    build: ./Django_NBA
    container_name: django_nba
    command: bash -c "
        python manage.py makemigrations 
        && python manage.py migrate
        && python manage.py runscript update_setup
        && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - POSTGRES_PASSWORD=djangonba
      - POSTGRES_HOST=nba.cdv1hhbg08am.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=NBA
    volumes:
      - type: bind
        source: ./Django_NBA/NBA
        target: /NBA
      - type: bind
        source: ./Django_NBA/scripts
        target: /scripts
    depends_on:
      - redis
  beat:
    build: ./Django_NBA
    command: bash -c " python manage.py runscript update_setup
        && celery -A NBA beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    container_name: beat_nba
    depends_on:
      - django
      - redis
      - celery
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - POSTGRES_PASSWORD=djangonba
      - POSTGRES_HOST=nba.cdv1hhbg08am.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=NBA
  celery:
    build: ./Django_NBA
    command: bash -c "python manage.py makemigrations 
        && python manage.py migrate 
        && celery -A NBA worker -l INFO"
    volumes:
      - type: bind
        source: ./Django_NBA/NBA
        target: /NBA
      - type: bind
        source: ./Django_NBA/scripts
        target: /scripts
    depends_on:
        - django
        - redis
    container_name: celery_nba
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - POSTGRES_PASSWORD=djangonba
      - POSTGRES_HOST=nba.cdv1hhbg08am.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=NBA
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"