# Generated by Django 4.2.1 on 2023-06-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_team_elo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('elo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('game_date', models.CharField(max_length=15)),
                ('wl', models.CharField(max_length=1)),
                ('opponent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Historical_team_elo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('date', models.CharField(max_length=15)),
                ('elo', models.BigIntegerField()),
            ],
        ),
    ]
