# Generated by Django 4.2.1 on 2023-06-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_team_elo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='current_team_elo',
            name='team_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='historical_team_elo',
            index=models.Index(fields=['team_id', 'date'], name='NBA_histori_team_id_bb5aca_idx'),
        ),
    ]
