# Generated by Django 4.2.1 on 2023-06-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0002_remove_current_team_elo_id_remove_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_team_elo',
            name='elo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historical_team_elo',
            name='elo',
            field=models.FloatField(),
        ),
    ]
