# Generated by Django 4.2.1 on 2023-06-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0003_alter_current_team_elo_elo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPlayerElo',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('elo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPlayerElo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('date', models.CharField(max_length=15)),
                ('elo', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Current_team_elo',
            new_name='CurrentTeamElo',
        ),
        migrations.RenameModel(
            old_name='Historical_team_elo',
            new_name='HistoricalTeamElo',
        ),
        migrations.RenameIndex(
            model_name='historicalteamelo',
            new_name='NBA_histori_team_id_884fda_idx',
            old_name='NBA_histori_team_id_bb5aca_idx',
        ),
        migrations.AddIndex(
            model_name='historicalplayerelo',
            index=models.Index(fields=['player_id', 'date'], name='NBA_histori_player__95d4b8_idx'),
        ),
    ]
