# Generated by Django 4.2.1 on 2023-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0004_currentplayerelo_historicalplayerelo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField()),
                ('wl', models.CharField(max_length=1)),
            ],
            options={
                'indexes': [models.Index(fields=['game_id', 'wl'], name='NBA_playerg_game_id_177c63_idx')],
            },
        ),
    ]
