# Generated by Django 4.2.1 on 2023-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0005_playergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergame',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playergame',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
