# Generated by Django 4.2.1 on 2023-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPlayerElo',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('elo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTeamElo',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('elo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('game_date', models.CharField(max_length=15)),
                ('wl', models.CharField(max_length=1)),
                ('opponent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('game_id', models.IntegerField()),
                ('wl', models.CharField(max_length=1)),
            ],
            options={
                'indexes': [models.Index(fields=['game_id', 'wl'], name='NBA_playerg_game_id_177c63_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTeamElo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('date', models.CharField(max_length=15)),
                ('elo', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['team_id', 'date'], name='NBA_histori_team_id_884fda_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlayerElo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('date', models.CharField(max_length=15)),
                ('elo', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['player_id', 'date'], name='NBA_histori_player__95d4b8_idx')],
            },
        ),
    ]
