apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx
  labels:
    app: ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngx
  template:
    metadata:
      labels:
        app: ngx
    spec:
      containers:
        - name: ngx
          image: nginxdemos/hello
          ports:
            - containerPort: 80     
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: LoadBalancer
  selector:
    app: ngx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80